apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-services-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: genai-services-site
  template:
    metadata:
      labels:
        app: genai-services-site
    spec:
      containers:
      - name: genai-services-site
        image: IMAGE_URL
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
        readinessProbe:
          httpGet:
            path: /health
  strategy:
    type: RollingUpdate
  imagePullPolicy: Always